// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6JaWXtsePrp2rO4iIgfroYXhMNeeWTWA',
    appId: '1:680892867686:web:660673712cf293c4bb39a7',
    messagingSenderId: '680892867686',
    projectId: 'grievance-c1705',
    authDomain: 'grievance-c1705.firebaseapp.com',
    storageBucket: 'grievance-c1705.firebasestorage.app',
    measurementId: 'G-QWSJMCRL5G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5BXTZLzbLpRJZL9l8CJ3HoqWs6YCH2FA',
    appId: '1:680892867686:android:62219d934739ea8fbb39a7',
    messagingSenderId: '680892867686',
    projectId: 'grievance-c1705',
    storageBucket: 'grievance-c1705.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC02wIjsJUGz47qn_S0nCdSp_ITx0EmUNQ',
    appId: '1:680892867686:ios:e9bd646312a95bd8bb39a7',
    messagingSenderId: '680892867686',
    projectId: 'grievance-c1705',
    storageBucket: 'grievance-c1705.firebasestorage.app',
    iosBundleId: 'com.grievance.system.ah.grievanceSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC02wIjsJUGz47qn_S0nCdSp_ITx0EmUNQ',
    appId: '1:680892867686:ios:e9bd646312a95bd8bb39a7',
    messagingSenderId: '680892867686',
    projectId: 'grievance-c1705',
    storageBucket: 'grievance-c1705.firebasestorage.app',
    iosBundleId: 'com.grievance.system.ah.grievanceSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6JaWXtsePrp2rO4iIgfroYXhMNeeWTWA',
    appId: '1:680892867686:web:6380871a29429cb8bb39a7',
    messagingSenderId: '680892867686',
    projectId: 'grievance-c1705',
    authDomain: 'grievance-c1705.firebaseapp.com',
    storageBucket: 'grievance-c1705.firebasestorage.app',
    measurementId: 'G-Z556KRPN8T',
  );
}
